version: '3.8'

volumes:
  mongo-data:

services:
  db:
    image: mongo:4.4.14
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}

  nginx:
    depends_on:
      - app
    ports:
      - '80:80'
      - '443:443'

  app:
    environment:
      MONGODB_URI: mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@db:27017
      MONGODB_COMMENTS_DB: db
      SENTRY_IGNORE_API_RESOLUTION_ERROR: 1
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 4Gb
